version: '3.8'

services:
  nodepay-app:
    image: astonlee6403/nodepay-app:latest
    environment:
      - NP_TOKEN=your_token
      # - USE_PROXY=true
      # - PROXY_LIST=['http://127.0.01:80','sockes4://127.0.0.1:455']
    restart: unless-stopped